---
title: "Homework Class 6 (R Functions)"
author: "Patricia Chen A16138722"
date: "04/27/23"
format: pdf
---

```{r}
library(bio3d)

# s1 <- read.pdb("4AKE")  # kinase with drug
# s2 <- read.pdb("1AKE")  # kinase no drug
# s3 <- read.pdb("1E4Y")  # kinase with drug
# 
# s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
# s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
# s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
# 
# s1.b <- s1.chainA$atom$b
# s2.b <- s2.chainA$atom$b
# s3.b <- s3.chainA$atom$b
# 
# plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
# plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
# plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")

```


## Shortened Function plotPDB()

```{r}
#' Plots Residue by Bfactor 
#'
#' @param x PDB code in quotes
#'
#' @return A line plot of Residue by Bfactor 
#' @export
#'
#' @examples
#' plotPDB("4AKE")
#' 
plotPDB <- function(x) {
  pdb <- read.pdb(x)
  
  #Trim PDB file so it only includes chain A and atom type CA
  pdb.chainA <- trim.pdb(pdb, chain="A", elety="CA")
  
  pdb.atom <- pdb.chainA$atom$b
  
  #Creates a line plot 
  plotb3(pdb.atom, sse=pdb.chainA, typ="l", ylab="Bfactor")
}
```
